Repository harakeke-2021/scoops., pull requests merged in 2021-02, with the labels that each got.

#4 add route, db data
  package.json
  server/db/migrations/20210212084109_orders.js
  server/db/migrations/20210212084120_orders_products.js
  server/db/migrations/20210212104723_products.js
  server/db/seeds/products.js
  server/public/images/choc-chips.jpg
  server/routes.js
  server/routes/ice-cream.js
  server/server.js
Labels: backend, enhancement

#7 fix db link
  server/routes/ice-cream.js
Labels: backend, bug

#12 add image links to database
  server/db/seeds/products.js
Labels: backend, enhancement

#13 add GET /api/v1/orders/ route
  server/routes/orders.js
  server/server.js
Labels: backend, enhancement

#16 Cones component
  client/components/Cone.jsx
  client/components/Cones.jsx
  client/components/Home.jsx
Labels: enhancement, frontend

#14 add POST /api/v1/orders route
  server/routes/orders.js
Labels: backend, enhancement
